name: check
on:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -W ignore::DeprecationWarning:discord.player -m pytest --cov=. --cov-report=xml --cov-report=term

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
  deploy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 202.181.188.48 >> ~/.ssh/known_hosts
      
      - name: Configure Git on server
        run: |
          ssh root@202.181.188.48 "cd /var/www/minebuild-site && \
          git config --global credential.helper store && \
          echo 'https://KOFIOK:${{ secrets.GITHUB_TOKEN }}@github.com' > ~/.git-credentials"
      
      - name: Pull latest changes
        run: |
          ssh root@202.181.188.48 "cd /var/www/minebuild-site && \
          git remote set-url origin https://KOFIOK:${{ secrets.GITHUB_TOKEN }}@github.com/KOFIOK/minebuild-site.git && \
          git pull"
      
      - name: Stop running processes
        continue-on-error: true
        run: |
          ssh root@202.181.188.48 "pkill -f 'python main.py' || true"
          ssh root@202.181.188.48 "pkill -f 'hypercorn' || true"
          ssh root@202.181.188.48 "sleep 2"
          
      - name: Cleanup screen sessions
        continue-on-error: true
        run: |
          ssh root@202.181.188.48 "screen -ls | grep -q 'minebuild' && screen -S minebuild -X quit || true"
          ssh root@202.181.188.48 "screen -wipe || true"
          
      - name: Start application
        run: |
          ssh root@202.181.188.48 "cd /var/www/minebuild-site && \
          source venv/bin/activate && \
          screen -dmS minebuild bash -c 'cd /var/www/minebuild-site && source venv/bin/activate && python main.py; exec bash'"
          
      - name: Clean up
        run: |
          rm -rf ~/.ssh/id_rsa