name: check
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -W ignore::DeprecationWarning:discord.player -m pytest --cov=. --cov-report=xml --cov-report=term

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
  deploy:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 202.181.188.48 >> ~/.ssh/known_hosts
          
          # Deploy to server
          ssh root@202.181.188.48 "cd /var/www/minebuild-site && \
          git config --global credential.helper store && \
          echo 'https://KOFIOK:${{ secrets.GITHUB_TOKEN }}@github.com/KOFIOK/minebuild-site.git' > ~/.git-credentials && \
          git remote set-url origin https://KOFIOK:${{ secrets.GITHUB_TOKEN }}@github.com/KOFIOK/minebuild-site.git && \
          git pull && \
          # Останавливаем существующий экземпляр, если он есть
          screen -S minebuild -X quit || true && \
          # Активируем виртуальное окружение и запускаем приложение в новом screen
          screen -dmS minebuild bash -c 'cd /var/www/minebuild-site && source venv/bin/activate && python main.py; exec bash'"
          
          # Clean up
          rm -rf ~/.ssh/id_rsa